ALTER SEQUENCE "restaurants_id_seq" MINVALUE 1 START 1 RESTART 1;
ALTER SEQUENCE "inventories_id_seq" MINVALUE 1 START 1 RESTART 1;
ALTER SEQUENCE "menus_id_seq" MINVALUE 1 START 1 RESTART 1;
ALTER SEQUENCE "ingredients_id_seq" MINVALUE 1 START 1 RESTART 1;
ALTER SEQUENCE "entries_id_seq" MINVALUE 1 START 1 RESTART 1;